#define MASK_RED 33640459
#define MASK_BLUE 33638411

#define FILE_RESTRICTEDWEAPONS "configs/sf2/restrictedweapons.cfg"
#define FILE_RESTRICTEDWEAPONS_DATA "data/sf2/restrictedweapons.cfg"

#define FILE_CLASSCONFIGS "configs/sf2/class_stats.cfg"
#define FILE_CLASSCONFIGS_DATA "data/sf2/class_stats.cfg"

#define CRIT_SOUND "player/crit_hit.wav"
#define CRIT_PARTICLENAME "crit_text"
#define MINICRIT_SOUND "player/crit_hit_mini.wav"
#define MINICRIT_PARTICLENAME "minicrit_text"
#define ZAP_SOUND ")weapons/barret_arm_zap.wav"
#define ZAP_PARTICLENAME "dxhr_arm_muzzleflash"
#define FIREWORKSBLU_PARTICLENAME "utaunt_firework_teamcolor_blue"
#define FIREWORKSRED_PARTICLENAME "utaunt_firework_teamcolor_red"
#define TELEPORTEDINBLU_PARTICLENAME "teleported_red"
#define SOUND_THUNDER ")ambient/explosions/explode_9.wav"
#define DEBUG_PAGEREVEALSOUND "#ui/cyoa_node_activate.wav"

#define SPECIAL1UPSOUND "mvm/mvm_revive.wav"

#define SPECIALROUND_BOO_DISTANCE 120.0
#define SPECIALROUND_BOO_DURATION 4.0

#define PAGE_DETECTOR_BEEP "items/cart_explode_trigger.wav"

#define PAGE_MODEL "models/slender/pickups/sheet.mdl"
#define PAGE_MODELSCALE 1.0

#define DEFAULT_CLOAKONSOUND ")weapons/medi_shield_deploy.wav"
#define DEFAULT_CLOAKOFFSOUND ")weapons/medi_shield_retract.wav"

#define SF_KEYMODEL "models/demani_sf/key_australium.mdl"

#define FLASHLIGHT_CLICKSOUND "slender/slenderflashlightclick.wav"
#define FLASHLIGHT_CLICKSOUND_NIGHTVISION "slender/nightvision.mp3"
#define FLASHLIGHT_BREAKSOUND "ambient/energy/spark6.wav"
#define FLASHLIGHT_NOSOUND "player/suit_denydevice.wav"
#define PAGE_GRABSOUND ")slender/slenderpagegrab.wav"

#define MUSIC_CHAN SNDCHAN_AUTO
#define MUSIC_GOTPAGES1_SOUND "slender/newambience_1.wav"
#define MUSIC_GOTPAGES2_SOUND "slender/newambience_2.wav"
#define MUSIC_GOTPAGES3_SOUND "slender/newambience_3.wav"
#define MUSIC_GOTPAGES4_SOUND "slender/newambience_4.wav"
#define MUSIC_PAGE_VOLUME 1.0

#define SF2_INTRO_DEFAULT_MUSIC "slender/intro.mp3"

#define PROXY_RAGE_MODE_SOUND "slender/proxyrage.mp3"

#define FIREBALL_SHOOT ")misc/halloween/spell_fireball_cast.wav"
#define FIREBALL_IMPACT ")misc/halloween/spell_fireball_impact.wav"
#define FIREBALL_TRAIL "spell_fireball_small_red"
#define ICEBALL_IMPACT ")weapons/icicle_freeze_victim_01.wav"
#define ICEBALL_TRAIL "spell_fireball_small_blue"
#define ROCKET_SHOOT ")weapons/rocket_shoot.wav"
#define ROCKET_IMPACT ")weapons/explode1.wav"
#define ROCKET_IMPACT2 ")weapons/explode2.wav"
#define ROCKET_IMPACT3 ")weapons/explode3.wav"
#define ROCKET_MODEL "models/weapons/w_models/w_rocket.mdl"
#define ROCKET_TRAIL "rockettrail"
#define ROCKET_EXPLODE_PARTICLE "ExplosionCore_MidAir"
#define GRENADE_SHOOT ")weapons/grenade_launcher_shoot.wav"
#define SENTRYROCKET_SHOOT ")weapons/sentry_rocket.wav"
#define ARROW_SHOOT ")weapons/bow_shoot.wav"
#define GRENADE_MODEL "models/weapons/w_models/w_grenade_grenadelauncher.mdl"
#define MANGLER_SHOOT ")weapons/cow_mangler_main_shot.wav"
#define MANGLER_EXPLODE1 ")weapons/cow_mangler_explosion_normal_01.wav"
#define MANGLER_EXPLODE2 ")weapons/cow_mangler_explosion_normal_02.wav"
#define MANGLER_EXPLODE3 ")weapons/cow_mangler_explosion_normal_03.wav"
#define BASEBALL_SHOOT ")weapons/bat_baseball_hit1.wav"
#define BASEBALL_MODEL "weapons/w_models/w_baseball.mdl"

#define JARATE_HITPLAYER ")weapons/jar_single.wav"
#define JARATE_PARTICLE "peejar_impact"
#define MILK_PARTICLE "peejar_impact_milk"
#define GAS_PARTICLE "gas_can_impact_blue"
#define STUN_HITPLAYER ")weapons/icicle_freeze_victim_01.wav"
#define STUN_PARTICLE "xms_icicle_melt"
#define ELECTRIC_RED_PARTICLE "electrocuted_gibbed_red"
#define ELECTRIC_BLUE_PARTICLE "electrocuted_gibbed_red"

//Page Rewards
#define EXPLODE_PLAYER "items/pumpkin_explode1.wav"
#define UBER_ROLL "misc/halloween/spell_overheal.wav"
#define NO_EFFECT_ROLL "player/taunt_sorcery_fail.wav"
#define BLEED_ROLL "items/powerup_pickup_plague_infected.wav"
#define CRIT_ROLL "items/powerup_pickup_crits.wav"
#define LOSE_SPRINT_ROLL "misc/banana_slip.wav"
#define JARATE_ROLL "weapons/jar_explode.wav"
#define GAS_ROLL "weapons/gas_can_explode.wav"

#define GENERIC_ROLL_TICK "ui/buttonrollover.wav"

#define MINICRIT_BUFF "weapons/buff_banner_flag.wav"

#define HYPERSNATCHER_NIGHTAMRE_1 "slender/snatcher/nightmare1.wav"
#define HYPERSNATCHER_NIGHTAMRE_2 "slender/snatcher/nightmare2.wav"
#define HYPERSNATCHER_NIGHTAMRE_3 "slender/snatcher/nightmare3.wav"
#define HYPERSNATCHER_NIGHTAMRE_4 "slender/snatcher/nightmare4.wav"
#define HYPERSNATCHER_NIGHTAMRE_5 "slender/snatcher/nightmare5.wav"
#define SNATCHER_APOLLYON_1 "slender/snatcher/apollyon1.wav"
#define SNATCHER_APOLLYON_2 "slender/snatcher/apollyon2.wav"
#define SNATCHER_APOLLYON_3 "slender/snatcher/apollyon3.wav"

#define RENEVANT_MAXWAVES 5

#define NULLSOUND "misc/null.wav"

#define NINETYSMUSIC "slender/sf2modified_runninginthe90s_v2.wav"

#define TRAP_DEPLOY ")slender/modified_traps/beartrap/trap_deploy.mp3"
#define TRAP_CLOSE ")slender/modified_traps/beartrap/trap_close.mp3"
#define TRAP_MODEL "models/mentrillum/traps/beartrap.mdl"

#define LASER_MODEL "sprites/laser.vmt"

#define THANATOPHOBIA_SCOUTNO "vo/scout_no03.mp3"
#define THANATOPHOBIA_SOLDIERNO "vo/soldier_no01.mp3"
#define THANATOPHOBIA_PYRONO "vo/pyro_no01.mp3"
#define THANATOPHOBIA_DEMOMANNO "vo/demoman_no03.mp3"
#define THANATOPHOBIA_HEAVYNO "vo/heavy_no02.mp3"
#define THANATOPHOBIA_ENGINEERNO "vo/engineer_no01.mp3"
#define THANATOPHOBIA_MEDICNO "vo/medic_no03.mp3"
#define THANATOPHOBIA_SNIPERNO "vo/sniper_no01.mp3"
#define THANATOPHOBIA_SPYNO "vo/spy_no02.mp3"

#define SF2_HUD_TEXT_COLOR_R 127
#define SF2_HUD_TEXT_COLOR_G 167
#define SF2_HUD_TEXT_COLOR_B 141
#define SF2_HUD_TEXT_COLOR_A 255

#define SF2_PROFILE_CHASER_DEFAULT_POSTURE "default"